export const AUTH_TOKEN = 'AUTH_TOKEN';
export const RECENTLY_VIEW_ITEMS = 'RECENTLY_VIEW_ITEMS';
export const WISHLIST_ITEMS = 'WISHLIST_ITEMS';
export const CART_ITEMS = 'CART_ITEMS';
export const CART_TOTAL_QUANTITY = 'CART_TOTAL_QUANTITY';